name: Check Open API Changes
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  api-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head

      - name: Check out main branch
        if: github.event.pull_request.base.ref == 'main'
        uses: actions/checkout@v2
        with:
          ref: main
          path: base

      - name: Check out dev branch
        if: github.event.pull_request.base.ref == 'dev'
        uses: actions/checkout@v2
        with:
          ref: dev
          path: base

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: allenheltondev/detect-breaking-changes-action@v1
        with:
          specFileName: api.json
          format: json
          breakingChangeTypes: |
            removed-paths
            schema-properties-removed
            parameters-removed
            schema-new-required-properties
            schema-type-changed
            schema-property-type-changed



      # - name: Run OpenAPI Diff (from HEAD revision)
      #   uses: mvegter/openapi-diff-action@v0.23.5
      #   with:
      #     head-spec: head/api.json
      #     base-spec: base/api.json


    #   - name: Compare OpenAPI Specs
    #   id: diff
    #   uses: oasdiff/oasdiff-action/breaking@main
    #   with:
    #     base: base/api.json
    #     revision: head/api.json

    # - name: Output Breaking Changes
    #   if: steps.diff.outputs.result != ''
    #   run: echo "${{ steps.diff.outputs.result }}"
    #   continue-on-error: true

    # - name: Fail if breaking changes are detected
    #   if: steps.diff.outputs.result != ''
    #   run: exit 1