name: Check Open API Changes
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  open-api-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head

      - name: Check out base branch
        if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'dev'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: base/api.json
          revision: head/api.json
          fail-on: ERR
          include-checks: api-operation-id-removed,api-schema-removed,request-body-enum-value-removed,response-mediatype-enum-value-removed,response-property-enum-value-removed
          include-path-params: true
          composed: false
          output-to-file: ./oasdiff-diff

      - name: Display diff result for debugging
        if: always()
        run: cat ./oasdiff-diff