name: Check Open API Changes
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  api-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head

      - name: Check out main branch
        if: github.event.pull_request.base.ref == 'main'
        uses: actions/checkout@v2
        with:
          ref: main
          path: base

      - name: Check out dev branch
        if: github.event.pull_request.base.ref == 'dev'
        uses: actions/checkout@v2
        with:
          ref: dev
          path: base

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/api.json
          base-spec: base/api.json

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install openapi-diff
        run: npm install -g @openapitools/openapi-diff

      - name: Run OpenAPI Diff (Check Enum)
        run: |
          openapi-diff base/api.json head/api.json > result.txt
          cat result.txt
          if grep -q "enum" result.txt; then
            echo "Breaking changes in enums detected"
            exit 1
          fi